import type { Language } from "@/hooks/usePreferences";

export type Letter = {
  char: string;
  name: string;
  example: string;
  exampleMeaning: string;
};

export const ALPHABETS: Record<Language, Letter[]> = {
  English: [
    { char: "A a", name: "ay", example: "Apple", exampleMeaning: "apple" },
    { char: "B b", name: "bee", example: "Book", exampleMeaning: "book" },
    { char: "C c", name: "see", example: "Cat", exampleMeaning: "cat" },
    { char: "D d", name: "dee", example: "Dog", exampleMeaning: "dog" },
    { char: "E e", name: "ee", example: "Egg", exampleMeaning: "egg" },
    { char: "F f", name: "ef", example: "Fish", exampleMeaning: "fish" },
    { char: "G g", name: "jee", example: "Goat", exampleMeaning: "goat" },
    { char: "H h", name: "aitch", example: "Hat", exampleMeaning: "hat" },
    { char: "I i", name: "eye", example: "Ice", exampleMeaning: "ice" },
    { char: "J j", name: "jay", example: "Jam", exampleMeaning: "jam" },
    { char: "K k", name: "kay", example: "Kite", exampleMeaning: "kite" },
    { char: "L l", name: "el", example: "Lion", exampleMeaning: "lion" },
    { char: "M m", name: "em", example: "Moon", exampleMeaning: "moon" },
    { char: "N n", name: "en", example: "Nest", exampleMeaning: "nest" },
    { char: "O o", name: "oh", example: "Orange", exampleMeaning: "orange" },
    { char: "P p", name: "pee", example: "Pen", exampleMeaning: "pen" },
    { char: "Q q", name: "cue", example: "Queen", exampleMeaning: "queen" },
    { char: "R r", name: "ar", example: "Rain", exampleMeaning: "rain" },
    { char: "S s", name: "ess", example: "Sun", exampleMeaning: "sun" },
    { char: "T t", name: "tee", example: "Tree", exampleMeaning: "tree" },
    { char: "U u", name: "you", example: "Umbrella", exampleMeaning: "umbrella" },
    { char: "V v", name: "vee", example: "Van", exampleMeaning: "van" },
    { char: "W w", name: "double-you", example: "Water", exampleMeaning: "water" },
    { char: "X x", name: "ex", example: "Box", exampleMeaning: "box" },
    { char: "Y y", name: "why", example: "Yellow", exampleMeaning: "yellow" },
    { char: "Z z", name: "zee", example: "Zebra", exampleMeaning: "zebra" },
  ],
  Spanish: [
    { char: "A a", name: "a", example: "Árbol", exampleMeaning: "tree" },
    { char: "B b", name: "be", example: "Boca", exampleMeaning: "mouth" },
    { char: "C c", name: "ce", example: "Casa", exampleMeaning: "house" },
    { char: "D d", name: "de", example: "Día", exampleMeaning: "day" },
    { char: "E e", name: "e", example: "Estrella", exampleMeaning: "star" },
    { char: "F f", name: "efe", example: "Flor", exampleMeaning: "flower" },
    { char: "G g", name: "ge", example: "Gato", exampleMeaning: "cat" },
    { char: "H h", name: "hache", example: "Hola", exampleMeaning: "hello" },
    { char: "I i", name: "i", example: "Isla", exampleMeaning: "island" },
    { char: "J j", name: "jota", example: "Jugar", exampleMeaning: "to play" },
    { char: "K k", name: "ka", example: "Kilo", exampleMeaning: "kilo" },
    { char: "L l", name: "ele", example: "Luna", exampleMeaning: "moon" },
    { char: "M m", name: "eme", example: "Mar", exampleMeaning: "sea" },
    { char: "N n", name: "ene", example: "Noche", exampleMeaning: "night" },
    { char: "Ñ ñ", name: "eñe", example: "Niño", exampleMeaning: "child" },
    { char: "O o", name: "o", example: "Ojo", exampleMeaning: "eye" },
    { char: "P p", name: "pe", example: "Pan", exampleMeaning: "bread" },
    { char: "Q q", name: "cu", example: "Queso", exampleMeaning: "cheese" },
    { char: "R r", name: "erre", example: "Rojo", exampleMeaning: "red" },
    { char: "S s", name: "ese", example: "Sol", exampleMeaning: "sun" },
    { char: "T t", name: "te", example: "Tierra", exampleMeaning: "earth" },
    { char: "U u", name: "u", example: "Uva", exampleMeaning: "grape" },
    { char: "V v", name: "uve", example: "Vino", exampleMeaning: "wine" },
    { char: "W w", name: "doble uve", example: "Wifi", exampleMeaning: "wifi" },
    { char: "X x", name: "equis", example: "Xilófono", exampleMeaning: "xylophone" },
    { char: "Y y", name: "ye", example: "Yo", exampleMeaning: "I" },
    { char: "Z z", name: "zeta", example: "Zorro", exampleMeaning: "fox" },
  ],
  French: [
    { char: "A a", name: "ah", example: "Ami", exampleMeaning: "friend" },
    { char: "B b", name: "bay", example: "Bonjour", exampleMeaning: "hello" },
    { char: "C c", name: "say", example: "Chat", exampleMeaning: "cat" },
    { char: "D d", name: "day", example: "Dent", exampleMeaning: "tooth" },
    { char: "E e", name: "uh", example: "École", exampleMeaning: "school" },
    { char: "F f", name: "eff", example: "Fleur", exampleMeaning: "flower" },
    { char: "G g", name: "zhay", example: "Glace", exampleMeaning: "ice" },
    { char: "H h", name: "ahsh", example: "Hibou", exampleMeaning: "owl" },
    { char: "I i", name: "ee", example: "Île", exampleMeaning: "island" },
    { char: "J j", name: "zhee", example: "Jour", exampleMeaning: "day" },
    { char: "K k", name: "kah", example: "Kiwi", exampleMeaning: "kiwi" },
    { char: "L l", name: "ell", example: "Lune", exampleMeaning: "moon" },
    { char: "M m", name: "em", example: "Maison", exampleMeaning: "house" },
    { char: "N n", name: "en", example: "Nuit", exampleMeaning: "night" },
    { char: "O o", name: "oh", example: "Oiseau", exampleMeaning: "bird" },
    { char: "P p", name: "pay", example: "Pain", exampleMeaning: "bread" },
    { char: "Q q", name: "koo", example: "Quatre", exampleMeaning: "four" },
    { char: "R r", name: "air", example: "Rouge", exampleMeaning: "red" },
    { char: "S s", name: "ess", example: "Soleil", exampleMeaning: "sun" },
    { char: "T t", name: "tay", example: "Terre", exampleMeaning: "earth" },
    { char: "U u", name: "ew", example: "Une", exampleMeaning: "one" },
    { char: "V v", name: "vay", example: "Vert", exampleMeaning: "green" },
    { char: "W w", name: "doo-bluh-vay", example: "Wagon", exampleMeaning: "wagon" },
    { char: "X x", name: "eeks", example: "Xylophone", exampleMeaning: "xylophone" },
    { char: "Y y", name: "ee grek", example: "Yeux", exampleMeaning: "eyes" },
    { char: "Z z", name: "zed", example: "Zèbre", exampleMeaning: "zebra" },
  ],
  German: [
    { char: "A a", name: "ah", example: "Apfel", exampleMeaning: "apple" },
    { char: "B b", name: "bay", example: "Buch", exampleMeaning: "book" },
    { char: "C c", name: "tsay", example: "Computer", exampleMeaning: "computer" },
    { char: "D d", name: "day", example: "Danke", exampleMeaning: "thanks" },
    { char: "E e", name: "ay", example: "Esel", exampleMeaning: "donkey" },
    { char: "F f", name: "eff", example: "Frau", exampleMeaning: "woman" },
    { char: "G g", name: "gay", example: "Garten", exampleMeaning: "garden" },
    { char: "H h", name: "hah", example: "Hund", exampleMeaning: "dog" },
    { char: "I i", name: "ee", example: "Insel", exampleMeaning: "island" },
    { char: "J j", name: "yot", example: "Jahr", exampleMeaning: "year" },
    { char: "K k", name: "kah", example: "Katze", exampleMeaning: "cat" },
    { char: "L l", name: "ell", example: "Lampe", exampleMeaning: "lamp" },
    { char: "M m", name: "em", example: "Mond", exampleMeaning: "moon" },
    { char: "N n", name: "en", example: "Nacht", exampleMeaning: "night" },
    { char: "O o", name: "oh", example: "Obst", exampleMeaning: "fruit" },
    { char: "P p", name: "pay", example: "Papier", exampleMeaning: "paper" },
    { char: "Q q", name: "koo", example: "Quelle", exampleMeaning: "source" },
    { char: "R r", name: "err", example: "Rot", exampleMeaning: "red" },
    { char: "S s", name: "ess", example: "Sonne", exampleMeaning: "sun" },
    { char: "T t", name: "tay", example: "Tisch", exampleMeaning: "table" },
    { char: "U u", name: "oo", example: "Uhr", exampleMeaning: "clock" },
    { char: "V v", name: "fow", example: "Vogel", exampleMeaning: "bird" },
    { char: "W w", name: "vay", example: "Wasser", exampleMeaning: "water" },
    { char: "X x", name: "iks", example: "Xylophon", exampleMeaning: "xylophone" },
    { char: "Y y", name: "ipsilon", example: "Yoga", exampleMeaning: "yoga" },
    { char: "Z z", name: "tset", example: "Zeit", exampleMeaning: "time" },
    { char: "Ä ä", name: "ae", example: "Äpfel", exampleMeaning: "apples" },
    { char: "Ö ö", name: "oe", example: "Öl", exampleMeaning: "oil" },
    { char: "Ü ü", name: "ue", example: "Über", exampleMeaning: "over" },
    { char: "ß", name: "es-zett", example: "Straße", exampleMeaning: "street" },
  ],
  Italian: [
    { char: "A a", name: "ah", example: "Albero", exampleMeaning: "tree" },
    { char: "B b", name: "bee", example: "Bocca", exampleMeaning: "mouth" },
    { char: "C c", name: "chee", example: "Casa", exampleMeaning: "house" },
    { char: "D d", name: "dee", example: "Donna", exampleMeaning: "woman" },
    { char: "E e", name: "eh", example: "Estate", exampleMeaning: "summer" },
    { char: "F f", name: "effe", example: "Fiore", exampleMeaning: "flower" },
    { char: "G g", name: "jee", example: "Gatto", exampleMeaning: "cat" },
    { char: "H h", name: "akka", example: "Hotel", exampleMeaning: "hotel" },
    { char: "I i", name: "ee", example: "Isola", exampleMeaning: "island" },
    { char: "L l", name: "elle", example: "Luna", exampleMeaning: "moon" },
    { char: "M m", name: "emme", example: "Mare", exampleMeaning: "sea" },
    { char: "N n", name: "enne", example: "Notte", exampleMeaning: "night" },
    { char: "O o", name: "oh", example: "Occhio", exampleMeaning: "eye" },
    { char: "P p", name: "pee", example: "Pane", exampleMeaning: "bread" },
    { char: "Q q", name: "koo", example: "Quattro", exampleMeaning: "four" },
    { char: "R r", name: "erre", example: "Rosso", exampleMeaning: "red" },
    { char: "S s", name: "esse", example: "Sole", exampleMeaning: "sun" },
    { char: "T t", name: "tee", example: "Terra", exampleMeaning: "earth" },
    { char: "U u", name: "oo", example: "Uva", exampleMeaning: "grape" },
    { char: "V v", name: "voo", example: "Vino", exampleMeaning: "wine" },
    { char: "Z z", name: "tseta", example: "Zucchero", exampleMeaning: "sugar" },
  ],
  Portuguese: [
    { char: "A a", name: "ah", example: "Amigo", exampleMeaning: "friend" },
    { char: "B b", name: "bay", example: "Bom", exampleMeaning: "good" },
    { char: "C c", name: "say", example: "Casa", exampleMeaning: "house" },
    { char: "D d", name: "day", example: "Dia", exampleMeaning: "day" },
    { char: "E e", name: "eh", example: "Escola", exampleMeaning: "school" },
    { char: "F f", name: "ef", example: "Flor", exampleMeaning: "flower" },
    { char: "G g", name: "zhay", example: "Gato", exampleMeaning: "cat" },
    { char: "H h", name: "agah", example: "Hoje", exampleMeaning: "today" },
    { char: "I i", name: "ee", example: "Ilha", exampleMeaning: "island" },
    { char: "J j", name: "zhota", example: "Janela", exampleMeaning: "window" },
    { char: "K k", name: "kah", example: "Karatê", exampleMeaning: "karate" },
    { char: "L l", name: "el", example: "Lua", exampleMeaning: "moon" },
    { char: "M m", name: "em", example: "Mar", exampleMeaning: "sea" },
    { char: "N n", name: "en", example: "Noite", exampleMeaning: "night" },
    { char: "O o", name: "oh", example: "Olho", exampleMeaning: "eye" },
    { char: "P p", name: "pay", example: "Pão", exampleMeaning: "bread" },
    { char: "Q q", name: "kay", example: "Queijo", exampleMeaning: "cheese" },
    { char: "R r", name: "err", example: "Rio", exampleMeaning: "river" },
    { char: "S s", name: "es", example: "Sol", exampleMeaning: "sun" },
    { char: "T t", name: "tay", example: "Terra", exampleMeaning: "earth" },
    { char: "U u", name: "oo", example: "Uva", exampleMeaning: "grape" },
    { char: "V v", name: "vay", example: "Verde", exampleMeaning: "green" },
    { char: "W w", name: "dabliu", example: "Wifi", exampleMeaning: "wifi" },
    { char: "X x", name: "shees", example: "Xícara", exampleMeaning: "cup" },
    { char: "Y y", name: "ipsilon", example: "Yoga", exampleMeaning: "yoga" },
    { char: "Z z", name: "zay", example: "Zebra", exampleMeaning: "zebra" },
  ],
  Japanese: [
    { char: "あ", name: "a", example: "あめ (ame)", exampleMeaning: "rain" },
    { char: "い", name: "i", example: "いぬ (inu)", exampleMeaning: "dog" },
    { char: "う", name: "u", example: "うみ (umi)", exampleMeaning: "sea" },
    { char: "え", name: "e", example: "えき (eki)", exampleMeaning: "station" },
    { char: "お", name: "o", example: "おちゃ (ocha)", exampleMeaning: "tea" },
    { char: "か", name: "ka", example: "かさ (kasa)", exampleMeaning: "umbrella" },
    { char: "き", name: "ki", example: "きって (kitte)", exampleMeaning: "stamp" },
    { char: "く", name: "ku", example: "くつ (kutsu)", exampleMeaning: "shoes" },
    { char: "け", name: "ke", example: "けむり (kemuri)", exampleMeaning: "smoke" },
    { char: "こ", name: "ko", example: "こども (kodomo)", exampleMeaning: "child" },
    { char: "さ", name: "sa", example: "さくら (sakura)", exampleMeaning: "cherry blossom" },
    { char: "し", name: "shi", example: "しろ (shiro)", exampleMeaning: "white" },
    { char: "す", name: "su", example: "すし (sushi)", exampleMeaning: "sushi" },
    { char: "せ", name: "se", example: "せかい (sekai)", exampleMeaning: "world" },
    { char: "そ", name: "so", example: "そら (sora)", exampleMeaning: "sky" },
    { char: "た", name: "ta", example: "たまご (tamago)", exampleMeaning: "egg" },
    { char: "ち", name: "chi", example: "ちず (chizu)", exampleMeaning: "map" },
    { char: "つ", name: "tsu", example: "つき (tsuki)", exampleMeaning: "moon" },
    { char: "て", name: "te", example: "てがみ (tegami)", exampleMeaning: "letter" },
    { char: "と", name: "to", example: "とり (tori)", exampleMeaning: "bird" },
    { char: "な", name: "na", example: "なつ (natsu)", exampleMeaning: "summer" },
    { char: "に", name: "ni", example: "にく (niku)", exampleMeaning: "meat" },
    { char: "ぬ", name: "nu", example: "ぬの (nuno)", exampleMeaning: "cloth" },
    { char: "ね", name: "ne", example: "ねこ (neko)", exampleMeaning: "cat" },
    { char: "の", name: "no", example: "のり (nori)", exampleMeaning: "seaweed" },
    { char: "は", name: "ha", example: "はな (hana)", exampleMeaning: "flower" },
    { char: "ひ", name: "hi", example: "ひと (hito)", exampleMeaning: "person" },
    { char: "ふ", name: "fu", example: "ふね (fune)", exampleMeaning: "boat" },
    { char: "へ", name: "he", example: "へや (heya)", exampleMeaning: "room" },
    { char: "ほ", name: "ho", example: "ほし (hoshi)", exampleMeaning: "star" },
    { char: "ま", name: "ma", example: "まど (mado)", exampleMeaning: "window" },
    { char: "み", name: "mi", example: "みず (mizu)", exampleMeaning: "water" },
    { char: "む", name: "mu", example: "むら (mura)", exampleMeaning: "village" },
    { char: "め", name: "me", example: "め (me)", exampleMeaning: "eye" },
    { char: "も", name: "mo", example: "もり (mori)", exampleMeaning: "forest" },
    { char: "や", name: "ya", example: "やま (yama)", exampleMeaning: "mountain" },
    { char: "ゆ", name: "yu", example: "ゆき (yuki)", exampleMeaning: "snow" },
    { char: "よ", name: "yo", example: "よる (yoru)", exampleMeaning: "night" },
    { char: "ら", name: "ra", example: "らく (raku)", exampleMeaning: "easy" },
    { char: "り", name: "ri", example: "りんご (ringo)", exampleMeaning: "apple" },
    { char: "る", name: "ru", example: "るす (rusu)", exampleMeaning: "absence" },
    { char: "れ", name: "re", example: "れきし (rekishi)", exampleMeaning: "history" },
    { char: "ろ", name: "ro", example: "ろうそく (rousoku)", exampleMeaning: "candle" },
    { char: "わ", name: "wa", example: "わたし (watashi)", exampleMeaning: "I" },
    { char: "を", name: "wo", example: "を", exampleMeaning: "object marker" },
    { char: "ん", name: "n", example: "ほん (hon)", exampleMeaning: "book" },
  ],
  Chinese: [
    { char: "一", name: "yī", example: "一个 (yīgè)", exampleMeaning: "one" },
    { char: "二", name: "èr", example: "二月 (èryuè)", exampleMeaning: "February" },
    { char: "三", name: "sān", example: "三人 (sānrén)", exampleMeaning: "three people" },
    { char: "人", name: "rén", example: "好人 (hǎorén)", exampleMeaning: "good person" },
    { char: "口", name: "kǒu", example: "门口 (ménkǒu)", exampleMeaning: "doorway" },
    { char: "日", name: "rì", example: "日本 (rìběn)", exampleMeaning: "Japan" },
    { char: "月", name: "yuè", example: "月亮 (yuèliang)", exampleMeaning: "moon" },
    { char: "水", name: "shuǐ", example: "喝水 (hēshuǐ)", exampleMeaning: "drink water" },
    { char: "火", name: "huǒ", example: "火车 (huǒchē)", exampleMeaning: "train" },
    { char: "山", name: "shān", example: "高山 (gāoshān)", exampleMeaning: "high mountain" },
    { char: "木", name: "mù", example: "木头 (mùtou)", exampleMeaning: "wood" },
    { char: "大", name: "dà", example: "大家 (dàjiā)", exampleMeaning: "everyone" },
    { char: "小", name: "xiǎo", example: "小心 (xiǎoxīn)", exampleMeaning: "careful" },
    { char: "中", name: "zhōng", example: "中国 (zhōngguó)", exampleMeaning: "China" },
    { char: "上", name: "shàng", example: "上面 (shàngmiàn)", exampleMeaning: "above" },
    { char: "下", name: "xià", example: "下面 (xiàmiàn)", exampleMeaning: "below" },
    { char: "我", name: "wǒ", example: "我们 (wǒmen)", exampleMeaning: "we" },
    { char: "你", name: "nǐ", example: "你好 (nǐhǎo)", exampleMeaning: "hello" },
    { char: "他", name: "tā", example: "他们 (tāmen)", exampleMeaning: "they" },
    { char: "好", name: "hǎo", example: "你好 (nǐhǎo)", exampleMeaning: "hello" },
    { char: "天", name: "tiān", example: "今天 (jīntiān)", exampleMeaning: "today" },
    { char: "学", name: "xué", example: "学校 (xuéxiào)", exampleMeaning: "school" },
    { char: "生", name: "shēng", example: "学生 (xuéshēng)", exampleMeaning: "student" },
    { char: "爱", name: "ài", example: "我爱你 (wǒ ài nǐ)", exampleMeaning: "I love you" },
    { char: "家", name: "jiā", example: "家人 (jiārén)", exampleMeaning: "family" },
  ],
  Korean: [
    { char: "ㄱ", name: "giyeok (g/k)", example: "가방 (gabang)", exampleMeaning: "bag" },
    { char: "ㄴ", name: "nieun (n)", example: "나 (na)", exampleMeaning: "I" },
    { char: "ㄷ", name: "digeut (d/t)", example: "다리 (dari)", exampleMeaning: "leg" },
    { char: "ㄹ", name: "rieul (r/l)", example: "라디오 (radio)", exampleMeaning: "radio" },
    { char: "ㅁ", name: "mieum (m)", example: "물 (mul)", exampleMeaning: "water" },
    { char: "ㅂ", name: "bieup (b/p)", example: "밥 (bap)", exampleMeaning: "rice" },
    { char: "ㅅ", name: "siot (s)", example: "사람 (saram)", exampleMeaning: "person" },
    { char: "ㅇ", name: "ieung (silent/ng)", example: "아이 (ai)", exampleMeaning: "child" },
    { char: "ㅈ", name: "jieut (j)", example: "집 (jip)", exampleMeaning: "house" },
    { char: "ㅊ", name: "chieut (ch)", example: "차 (cha)", exampleMeaning: "tea" },
    { char: "ㅋ", name: "kieuk (k)", example: "커피 (keopi)", exampleMeaning: "coffee" },
    { char: "ㅌ", name: "tieut (t)", example: "토끼 (tokki)", exampleMeaning: "rabbit" },
    { char: "ㅍ", name: "pieup (p)", example: "포도 (podo)", exampleMeaning: "grape" },
    { char: "ㅎ", name: "hieut (h)", example: "하늘 (haneul)", exampleMeaning: "sky" },
    { char: "ㅏ", name: "a", example: "아빠 (appa)", exampleMeaning: "dad" },
    { char: "ㅑ", name: "ya", example: "야구 (yagu)", exampleMeaning: "baseball" },
    { char: "ㅓ", name: "eo", example: "어머니 (eomeoni)", exampleMeaning: "mother" },
    { char: "ㅕ", name: "yeo", example: "여자 (yeoja)", exampleMeaning: "woman" },
    { char: "ㅗ", name: "o", example: "오빠 (oppa)", exampleMeaning: "older brother" },
    { char: "ㅛ", name: "yo", example: "요리 (yori)", exampleMeaning: "cooking" },
    { char: "ㅜ", name: "u", example: "우유 (uyu)", exampleMeaning: "milk" },
    { char: "ㅠ", name: "yu", example: "유리 (yuri)", exampleMeaning: "glass" },
    { char: "ㅡ", name: "eu", example: "음악 (eumak)", exampleMeaning: "music" },
    { char: "ㅣ", name: "i", example: "이름 (ireum)", exampleMeaning: "name" },
  ],
  Arabic: [
    { char: "ا", name: "alif (a)", example: "أب (ab)", exampleMeaning: "father" },
    { char: "ب", name: "ba (b)", example: "باب (bab)", exampleMeaning: "door" },
    { char: "ت", name: "ta (t)", example: "تفاحة (tuffaha)", exampleMeaning: "apple" },
    { char: "ث", name: "tha (th)", example: "ثلج (thalj)", exampleMeaning: "snow" },
    { char: "ج", name: "jim (j)", example: "جمل (jamal)", exampleMeaning: "camel" },
    { char: "ح", name: "ha (ḥ)", example: "حب (hubb)", exampleMeaning: "love" },
    { char: "خ", name: "kha (kh)", example: "خبز (khubz)", exampleMeaning: "bread" },
    { char: "د", name: "dal (d)", example: "دار (dar)", exampleMeaning: "home" },
    { char: "ذ", name: "dhal (dh)", example: "ذهب (dhahab)", exampleMeaning: "gold" },
    { char: "ر", name: "ra (r)", example: "رجل (rajul)", exampleMeaning: "man" },
    { char: "ز", name: "zay (z)", example: "زيت (zayt)", exampleMeaning: "oil" },
    { char: "س", name: "sin (s)", example: "سماء (sama)", exampleMeaning: "sky" },
    { char: "ش", name: "shin (sh)", example: "شمس (shams)", exampleMeaning: "sun" },
    { char: "ص", name: "sad (ṣ)", example: "صديق (sadiq)", exampleMeaning: "friend" },
    { char: "ض", name: "dad (ḍ)", example: "ضوء (daw')", exampleMeaning: "light" },
    { char: "ط", name: "ta (ṭ)", example: "طفل (tifl)", exampleMeaning: "child" },
    { char: "ظ", name: "za (ẓ)", example: "ظهر (zuhr)", exampleMeaning: "noon" },
    { char: "ع", name: "ayn", example: "عين (ayn)", exampleMeaning: "eye" },
    { char: "غ", name: "ghayn (gh)", example: "غرفة (ghurfa)", exampleMeaning: "room" },
    { char: "ف", name: "fa (f)", example: "فم (fam)", exampleMeaning: "mouth" },
    { char: "ق", name: "qaf (q)", example: "قمر (qamar)", exampleMeaning: "moon" },
    { char: "ك", name: "kaf (k)", example: "كتاب (kitab)", exampleMeaning: "book" },
    { char: "ل", name: "lam (l)", example: "ليل (layl)", exampleMeaning: "night" },
    { char: "م", name: "mim (m)", example: "ماء (ma')", exampleMeaning: "water" },
    { char: "ن", name: "nun (n)", example: "نهر (nahr)", exampleMeaning: "river" },
    { char: "ه", name: "ha (h)", example: "هواء (hawa')", exampleMeaning: "air" },
    { char: "و", name: "waw (w)", example: "ورد (ward)", exampleMeaning: "rose" },
    { char: "ي", name: "ya (y)", example: "يد (yad)", exampleMeaning: "hand" },
  ],
  Russian: [
    { char: "А а", name: "a", example: "Арбуз", exampleMeaning: "watermelon" },
    { char: "Б б", name: "be", example: "Брат", exampleMeaning: "brother" },
    { char: "В в", name: "ve", example: "Вода", exampleMeaning: "water" },
    { char: "Г г", name: "ge", example: "Город", exampleMeaning: "city" },
    { char: "Д д", name: "de", example: "Дом", exampleMeaning: "house" },
    { char: "Е е", name: "ye", example: "Еда", exampleMeaning: "food" },
    { char: "Ё ё", name: "yo", example: "Ёлка", exampleMeaning: "fir tree" },
    { char: "Ж ж", name: "zhe", example: "Жизнь", exampleMeaning: "life" },
    { char: "З з", name: "ze", example: "Звезда", exampleMeaning: "star" },
    { char: "И и", name: "i", example: "Игра", exampleMeaning: "game" },
    { char: "Й й", name: "i kratkoye", example: "Май", exampleMeaning: "May" },
    { char: "К к", name: "ka", example: "Кот", exampleMeaning: "cat" },
    { char: "Л л", name: "el", example: "Луна", exampleMeaning: "moon" },
    { char: "М м", name: "em", example: "Мама", exampleMeaning: "mother" },
    { char: "Н н", name: "en", example: "Небо", exampleMeaning: "sky" },
    { char: "О о", name: "o", example: "Окно", exampleMeaning: "window" },
    { char: "П п", name: "pe", example: "Папа", exampleMeaning: "father" },
    { char: "Р р", name: "er", example: "Река", exampleMeaning: "river" },
    { char: "С с", name: "es", example: "Солнце", exampleMeaning: "sun" },
    { char: "Т т", name: "te", example: "Тигр", exampleMeaning: "tiger" },
    { char: "У у", name: "u", example: "Утро", exampleMeaning: "morning" },
    { char: "Ф ф", name: "ef", example: "Фрукт", exampleMeaning: "fruit" },
    { char: "Х х", name: "ha", example: "Хлеб", exampleMeaning: "bread" },
    { char: "Ц ц", name: "tse", example: "Цветок", exampleMeaning: "flower" },
    { char: "Ч ч", name: "che", example: "Час", exampleMeaning: "hour" },
    { char: "Ш ш", name: "sha", example: "Школа", exampleMeaning: "school" },
    { char: "Щ щ", name: "shcha", example: "Щит", exampleMeaning: "shield" },
    { char: "Ъ ъ", name: "tvyordy znak", example: "Объект", exampleMeaning: "object" },
    { char: "Ы ы", name: "y", example: "Сын", exampleMeaning: "son" },
    { char: "Ь ь", name: "myagky znak", example: "Соль", exampleMeaning: "salt" },
    { char: "Э э", name: "e", example: "Этаж", exampleMeaning: "floor" },
    { char: "Ю ю", name: "yu", example: "Юг", exampleMeaning: "south" },
    { char: "Я я", name: "ya", example: "Яблоко", exampleMeaning: "apple" },
  ],
  Hindi: [
    { char: "अ", name: "a", example: "अनार (anaar)", exampleMeaning: "pomegranate" },
    { char: "आ", name: "aa", example: "आम (aam)", exampleMeaning: "mango" },
    { char: "इ", name: "i", example: "इमली (imli)", exampleMeaning: "tamarind" },
    { char: "ई", name: "ee", example: "ईख (eekh)", exampleMeaning: "sugarcane" },
    { char: "उ", name: "u", example: "उल्लू (ullu)", exampleMeaning: "owl" },
    { char: "ऊ", name: "oo", example: "ऊन (oon)", exampleMeaning: "wool" },
    { char: "ए", name: "e", example: "एक (ek)", exampleMeaning: "one" },
    { char: "ऐ", name: "ai", example: "ऐनक (ainak)", exampleMeaning: "glasses" },
    { char: "ओ", name: "o", example: "ओखली (okhli)", exampleMeaning: "mortar" },
    { char: "औ", name: "au", example: "औरत (aurat)", exampleMeaning: "woman" },
    { char: "क", name: "ka", example: "कमल (kamal)", exampleMeaning: "lotus" },
    { char: "ख", name: "kha", example: "खरगोश (khargosh)", exampleMeaning: "rabbit" },
    { char: "ग", name: "ga", example: "गाय (gaay)", exampleMeaning: "cow" },
    { char: "घ", name: "gha", example: "घर (ghar)", exampleMeaning: "home" },
    { char: "च", name: "cha", example: "चाय (chai)", exampleMeaning: "tea" },
    { char: "छ", name: "chha", example: "छाता (chhata)", exampleMeaning: "umbrella" },
    { char: "ज", name: "ja", example: "जल (jal)", exampleMeaning: "water" },
    { char: "झ", name: "jha", example: "झंडा (jhanda)", exampleMeaning: "flag" },
    { char: "ट", name: "ṭa", example: "टमाटर (tamatar)", exampleMeaning: "tomato" },
    { char: "ठ", name: "ṭha", example: "ठंडा (thanda)", exampleMeaning: "cold" },
    { char: "ड", name: "ḍa", example: "डाल (daal)", exampleMeaning: "branch" },
    { char: "ढ", name: "ḍha", example: "ढोल (dhol)", exampleMeaning: "drum" },
    { char: "ण", name: "ṇa", example: "बाण (baan)", exampleMeaning: "arrow" },
    { char: "त", name: "ta", example: "तारा (tara)", exampleMeaning: "star" },
    { char: "थ", name: "tha", example: "थाली (thali)", exampleMeaning: "plate" },
    { char: "द", name: "da", example: "दिन (din)", exampleMeaning: "day" },
    { char: "ध", name: "dha", example: "धन (dhan)", exampleMeaning: "wealth" },
    { char: "न", name: "na", example: "नदी (nadi)", exampleMeaning: "river" },
    { char: "प", name: "pa", example: "पानी (paani)", exampleMeaning: "water" },
    { char: "फ", name: "pha", example: "फल (phal)", exampleMeaning: "fruit" },
    { char: "ब", name: "ba", example: "बच्चा (bachcha)", exampleMeaning: "child" },
    { char: "भ", name: "bha", example: "भालू (bhalu)", exampleMeaning: "bear" },
    { char: "म", name: "ma", example: "माँ (maa)", exampleMeaning: "mother" },
    { char: "य", name: "ya", example: "यार (yaar)", exampleMeaning: "friend" },
    { char: "र", name: "ra", example: "राजा (raja)", exampleMeaning: "king" },
    { char: "ल", name: "la", example: "लड़का (ladka)", exampleMeaning: "boy" },
    { char: "व", name: "va", example: "वन (van)", exampleMeaning: "forest" },
    { char: "श", name: "sha", example: "शेर (sher)", exampleMeaning: "lion" },
    { char: "ष", name: "ṣha", example: "षट्कोण (shatkon)", exampleMeaning: "hexagon" },
    { char: "स", name: "sa", example: "सूरज (suraj)", exampleMeaning: "sun" },
    { char: "ह", name: "ha", example: "हाथी (haathi)", exampleMeaning: "elephant" },
  ],
  Dutch: [
    { char: "A a", name: "ah", example: "Appel", exampleMeaning: "apple" },
    { char: "B b", name: "bay", example: "Boek", exampleMeaning: "book" },
    { char: "C c", name: "say", example: "Cadeau", exampleMeaning: "gift" },
    { char: "D d", name: "day", example: "Deur", exampleMeaning: "door" },
    { char: "E e", name: "ay", example: "Eend", exampleMeaning: "duck" },
    { char: "F f", name: "ef", example: "Fiets", exampleMeaning: "bicycle" },
    { char: "G g", name: "khay", example: "Goed", exampleMeaning: "good" },
    { char: "H h", name: "hah", example: "Huis", exampleMeaning: "house" },
    { char: "I i", name: "ee", example: "Ijs", exampleMeaning: "ice" },
    { char: "J j", name: "yay", example: "Jas", exampleMeaning: "coat" },
    { char: "K k", name: "kah", example: "Kat", exampleMeaning: "cat" },
    { char: "L l", name: "el", example: "Licht", exampleMeaning: "light" },
    { char: "M m", name: "em", example: "Maan", exampleMeaning: "moon" },
    { char: "N n", name: "en", example: "Nacht", exampleMeaning: "night" },
    { char: "O o", name: "oh", example: "Oog", exampleMeaning: "eye" },
    { char: "P p", name: "pay", example: "Paard", exampleMeaning: "horse" },
    { char: "Q q", name: "kew", example: "Quiz", exampleMeaning: "quiz" },
    { char: "R r", name: "er", example: "Rood", exampleMeaning: "red" },
    { char: "S s", name: "es", example: "School", exampleMeaning: "school" },
    { char: "T t", name: "tay", example: "Tafel", exampleMeaning: "table" },
    { char: "U u", name: "ew", example: "Uur", exampleMeaning: "hour" },
    { char: "V v", name: "fay", example: "Vis", exampleMeaning: "fish" },
    { char: "W w", name: "vay", example: "Water", exampleMeaning: "water" },
    { char: "X x", name: "iks", example: "Xylofoon", exampleMeaning: "xylophone" },
    { char: "Y y", name: "ee-grek", example: "Yoga", exampleMeaning: "yoga" },
    { char: "Z z", name: "zet", example: "Zon", exampleMeaning: "sun" },
  ],
};

export const RTL_LANGUAGES: Language[] = ["Arabic"];
