uploads = []
outputs = []

[[generated]]
id = "lbNcYXRpz896I2OnA2QN1"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "UiSUl9y2I4cgYwV4jwATN"
uri = "file://artifacts/mobile/assets/images/path-speech-bubble.png"
type = "image"
title = "soft blue speech bubble"

[[generated]]
id = "iZp7cGKrBSzAhO2f93Ot5"
uri = "file://artifacts/mobile/assets/images/path-ai-robot.png"
type = "image"
title = "cartoon ai robot mascot"
